url='https://a-pd-url.translations.com/PD'
username='a-pd-username'
password='a-pd-password'
userAgent='GLC.PY Sample Code Test'
sourceLanguage='source-LANG'
targetLanguages=['target-LANG1,target-LANG2']
project='PROJECT_SHORTCODE'
fileFormatProfile='FileDescriptor'
submissionPrefix='Test_PY_'
